---

- hosts:  webservers
  become: yes

  tasks:
    - name: Installation of latest version of nginx server
      apt:
        update_cache: yes
        name: nginx
        state:  latest

    - name: Default configuration of nginx server
      template:
        src:  default
        dest: /etc/nginx/sites-available/default

    - name: Restart the nginx servers
      service:
        name: nginx
        state:  restarted 

    - name: Install PHP packages
      apt:
        update_cache: yes
        name:
          - php
          - php-fpm
        state:  latest

    - name: Move index.php file to servers (/var/www/html)
      copy:
        src: webpages/index.php
        dest: /var/www/html/

- hosts:  haproxy
  become: yes

  tasks:

    - name: Installation of haproxy server
      apt:
        update_cache: yes
        name: haproxy
        state:  latest

    - name: HAproxy configuration
      template:
        src:  haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg

    - name: Restart the load balancer
      service:
        name: haproxy
        state:  restarted

