---

- hosts:  webservers
  become: yes

  tasks:
    - name: Installation of latest version of nginx server
      apt:
        update_cache: yes
        name: nginx
        state:  latest

    - name: Default configuration of nginx server
      template:
        src:  default
        dest: /etc/nginx/sites-available/default

    - name: Restart the nginx servers
      service:
        name: nginx
        state:  restarted 

    - name: Install PHP packages
      apt:
        update_cache: yes
        name:
          - php
          - php-fpm
        state:  latest

